name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- python=3.10
- bzip2
- pbmm2<=1.13
- seqkit<=2.5.1
- samtools
- pbsv<=2.9.0
- bcftools
- bedtools<=2.31
- whatshap<=2.1
- qualimap<=2.3
- pip
- pip:
  - matplotlib
  - seaborn
  - pyarrow
  - pandas
